const sampleData = [
    {
      name: "Raj's Villa",
      description: "A spacious villa located in the peaceful outskirts, ideal for family getaways.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      },
      price: 25000,
      location: "Pune",
      country: "India",
      category:"Mansion",
    },
    {
      name: "Luxury House",
      description: "An exquisite luxury house with modern amenities and a stunning view of the city skyline.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1628744448840-55bdb2497bd4?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGJpZyUyMGhvdXNlfGVufDB8fDB8fHww",
      },
      price: 30000,
      location: "Mumbai",
      country: "India",
      category:"Mansion",
    },
    {
      name: "Mountain Retreat",
      description: "A cozy retreat nestled in the mountains, perfect for a quiet and serene holiday.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1665735628022-9f607ce31e58?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGJpZyUyMGhvdXNlfGVufDB8fDB8fHww",
      },
      price: 18000,
      location: "Manali",
      country: "India",
      category:"Camping",
    },
    {
      name: "Cozy Beachfront",
      description: "A charming beachfront property with direct access to the ocean and a private beach area.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1685648628650-63740d39bffc?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHZpbGxhfGVufDB8fDB8fHww",
      },
      price: 28000,
      location: "Goa",
      country: "India",
      category:"Pool",
    },
    {
      name: "Sunny Apartment",
      description: "A bright and sunny apartment located in the city center with easy access to local amenities.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1597682496035-b04f723202a4?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjJ8fHZpbGxhfGVufDB8fDB8fHww",
      },
      price: 22000,
      location: "Bengaluru",
      country: "India",
      category:"Castle",
    },
    {
      name: "Hilltop Cottage",
      description: "A picturesque hilltop cottage with stunning views of the valley below.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1641317700714-f1836a888765?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8YmlnJTIwaG91c2V8ZW58MHx8MHx8fDA%3D",
      },
      price: 15000,
      location: "Ooty",
      country: "India",
      category:"Rooms",
    },
    {
      name: "Urban Studio",
      description: "A sleek, modern studio apartment located in the bustling downtown area, perfect for singles or couples.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1562239409-b5c79828df9e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjR8fHZpbGxhfGVufDB8fDB8fHww",
      },
      price: 12000,
      location: "New Delhi",
      country: "India",
      category:"Arctic",
    },
    {
      name: "Riverside Cottage",
      description: "A tranquil riverside cottage perfect for nature lovers, with access to scenic hiking trails.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1582610191340-fa501e6e5040?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjZ8fHZpbGxhfGVufDB8fDB8fHww",
      },
      price: 17000,
      location: "Rishikesh",
      country: "India",
      category:"MountainCity",
    },
    {
      name: "Beachside Villa",
      description: "A luxurious villa right by the beach, offering breathtaking views of the sea and direct beach access.",
      image: {
        filename:"listingimage",
        url: "https://plus.unsplash.com/premium_photo-1682377521741-66b111791809?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjV8fHZpbGxhfGVufDB8fDB8fHww",
      },
      price: 27000,
      location: "Chennai",
      country: "India",
      category:"Arctic",
    },
    {
      name: "Rustic Farmhouse",
      description: "A rustic farmhouse surrounded by acres of greenery, offering an authentic countryside experience.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1702817727742-d5d9f092b709?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjN8fHZpbGxhfGVufDB8fDB8fHww",
      },
      price: 23000,
      location: "Alibaug",
      country: "India",
      category:"Mansion",
    },
    {
      name: "Modern Duplex",
      description: "A stylish modern duplex with open-plan living spaces and a private rooftop terrace.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1628744448953-89b6b70965c7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGJpZyUyMGhvdXNlfGVufDB8fDB8fHww",
      },
      price: 22000,
      location: "Hyderabad",
      country: "India",
      category:"Beachfront",
    },
    {
      name: "Heritage Bungalow",
      description: "A historic bungalow with traditional architecture and expansive gardens.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1616012760010-8da02da071fd?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjh8fHZpbGxhfGVufDB8fDB8fHww",
      },
      price: 26000,
      location: "Jaipur",
      country: "India",
      category:"Arctic",
    },
    {
      name: "Lakeview House",
      description: "A peaceful house offering stunning views of the lake and surrounding forests.",
      image: {
        filename:"listingimage",
        url: "https://plus.unsplash.com/premium_photo-1661963657305-f52dcaeef418?q=80&w=1824&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      },
      price: 20000,
      location: "Nainital",
      country: "India",
      category:"Arctic",
    },
    {
      name: "Penthouse Suite",
      description: "A luxurious penthouse with panoramic views of the city, featuring private elevators and a pool.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1686769094976-2b48b8a59e82?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      },
      price: 30000,
      location: "Kolkata",
      country: "India",
      category:"Arctic",
    },
    {
      name: "Countryside Estate",
      description: "A large estate home with vast farmland and a serene rural environment.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1717245232615-13e7a75a8f73?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzZ8fHZpbGxhfGVufDB8fDB8fHww",
      },
      price: 28000,
      location: "Coorg",
      country: "India",
      category:"Arctic",
    },
    {
      name: "Secluded Villa",
      description: "A private villa located in a remote area, offering complete seclusion and tranquility.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1705831184069-a630053db454?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDN8fHZpbGxhfGVufDB8fDB8fHww",
      },
      price: 24000,
      location: "Wayanad",
      country: "India",
      category:"Farms",
    },
    {
      name: "Cliffside Cottage",
      description: "A unique cottage built on a cliffside, offering dramatic views of the ocean below.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1693466800653-9eb917c0552e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTF8fHZpbGxhfGVufDB8fDB8fHww",
      },
      price: 29000,
      location: "Varkala",
      country: "India",
      category:"Farms",
    },
    {
      name: "City Loft",
      description: "A modern loft-style apartment located in the heart of the city’s most vibrant neighborhood.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1692736933760-8a8a9b8c1b6f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTV8fHZpbGxhfGVufDB8fDB8fHww",
      },
      price: 18000,
      location: "Gurgaon",
      country: "India",
      category:"Camping",
    },
    {
      name: "Hillside Cabin",
      description: "A cozy cabin tucked into the hillside, perfect for a weekend escape into nature.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1670718668686-0d0cedbbfc9c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NjB8fHZpbGxhfGVufDB8fDB8fHww",
      },        
      price: 16000,
      location: "Shimla",
      country: "India",
      category:"Camping",
    },
    {
      name: "Luxury Resort",
      description: "An expansive luxury resort with private beach access and a full suite of amenities.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1725964483809-0f397051ab81?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGJlYWNoaG91c2V8ZW58MHx8MHx8fDA%3D",
      },
      price: 30000,
      location: "Kerala",
      country: "India",
      category:"Camping",
    },
    {
      name: "City Penthouse",
      description: "A top-floor penthouse with a large terrace and stunning views of the city skyline.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1534655610770-dd69616f05ff?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGJlYWNoaG91c2V8ZW58MHx8MHx8fDA%3D",
      },
      price: 29000,
      location: "Ahmedabad",
      country: "India",
      category:"Pool",
    },
    {
      name: "Forest Bungalow",
      description: "A serene bungalow set in the middle of a dense forest, perfect for a nature retreat.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1653525270525-232998ebed76?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDB8fGJlYWNoaG91c2V8ZW58MHx8MHx8fDA%3D",
      },
      price: 23000,
      location: "Shillong",
      country: "India",
      category:"Castle",
    },
    {
      name: "Coastal Cottage",
      description: "A quaint cottage by the sea, offering direct access to the beach and fantastic sunset views.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1581186467968-6ca780e6d2d9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mzl8fGJlYWNoaG91c2V8ZW58MHx8MHx8fDA%3D",
      },
      price: 21000,
      location: "Pondicherry",
      country: "India",
      category:"MountainCity",
    },
    {
      name: "Luxury Chalet",
      description: "A high-end chalet in the mountains, equipped with all modern comforts and breathtaking views.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1494526585095-c41746248156?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      },
      price: 30000,
      location: "Leh",
      country: "India",
      category:"Mansion",
    },
    {
      name: "Artist's Loft",
      description: "An open and airy loft designed for creatives, featuring large windows and natural light.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8aG91c2V8ZW58MHx8MHx8fDA%3D",
      },
      price: 18000,
      location: "Pune",
      country: "India",
      category:"Rooms",
    },
    {
      name: "Serene Cottage",
      description: "A small and peaceful cottage located in the middle of a quiet, rural village.",
      image: {
        filename:"listingimage",
        url: "https://plus.unsplash.com/premium_photo-1661876449499-26de7959878f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fGhvdXNlfGVufDB8fDB8fHww",
      },
      price: 15000,
      location: "Kodaikanal",
      country: "India",
      category:"Beachfront",
    },
    {
      name: "Contemporary House",
      description: "A modern house with sleek design and minimalistic interiors, located in a residential neighborhood.",
      image: {
        filename:"listingimage",
        url: "https://plus.unsplash.com/premium_photo-1661876449499-26de7959878f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fGhvdXNlfGVufDB8fDB8fHww",
      },
      price: 22000,
      location: "Chandigarh",
      country: "India",
      category:"Beachfront",
    },
    {
      name: "Eco-Friendly Cabin",
      description: "A sustainable cabin built using eco-friendly materials, with minimal impact on the environment.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1675870191244-d8251ef604d7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGJpZyUyMGhvdXNlfGVufDB8fDB8fHww",
      },
      price: 17000,
      location: "Mysuru",
      country: "India",
      category:"Beachfront",
    },
    {
      name: "Family Home",
      description: "A spacious family home with a large backyard, perfect for kids and pets.",
      image: {
        filename:"listingimage",
        url: "https://images.unsplash.com/photo-1465301055284-72f355cfd745?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGhvdXNlfGVufDB8fDB8fHww",
      },
      price: 20000,
      location: "Lucknow",
      country: "India",
      category:"Beachfront",
    },
    {
      name: "Beach Bungalow",
      description: "A stylish bungalow located right on the beach, offering unparalleled views of the ocean.",
      image: {
        filename:"listingimage",
        url:"https://images.unsplash.com/photo-1501635238895-63f29cfc06b3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdXNlfGVufDB8fDB8fHww",
      },
      price: 29000,
      location: "Andaman Islands",
      country: "India",
      category:"Beachfront",
    }
  ];
  
  module.exports = { data: sampleData };
  